services:
  - type: web
    name: self-attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: mysql://root:yajsocYrrqsYQrDgKEGjgwefcKAJeRuY@shortline.proxy.rlwy.net:27301/railway
        fromDatabase:
          name: railway
          type: mysql
          property: connectionString
