# Generated by Django 5.1.4 on 2025-02-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_superadmin_last_login_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('crc_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.PositiveIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
