# Generated by Django 5.1.4 on 2025-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='employee_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crc',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crc',
            name='year',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
