# Generated by Django 5.1.4 on 2025-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='crc_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='crc',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='crc',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='crc_users_permissions', to='auth.permission'),
        ),
    ]
