# Generated by Django 5.1.4 on 2025-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crc', '0002_crc_groups_crc_is_superuser_crc_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crc',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crc',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='crc_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='crc',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crc',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crc',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='crc_permissions', to='auth.permission'),
        ),
    ]
