# Generated by Django 5.1.4 on 2025-02-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0002_crc_employee_id_crc_semester_crc_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crc',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='crc',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='crc',
            name='year',
        ),
    ]
