# Generated by Django 5.1.4 on 2025-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0002_subject_timetableentry_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='entries',
            field=models.ManyToManyField(related_name='timetables', to='crc.timetableentry'),
        ),
    ]
