# Generated by Django 5.1.4 on 2025-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0002_subject_timetableentry_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='crcprofile',
            name='academic_year',
            field=models.CharField(default='2021-2025', max_length=20),
            preserve_default=False,
        ),
    ]
