# Generated by Django 5.1.4 on 2025-03-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
        ('crc', '0003_crcprofile_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crcprofile',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
    ]
