# Generated by Django 5.1.4 on 2025-02-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0003_crc_is_active_crc_is_staff_alter_crc_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='crc',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='crc',
            name='user_permissions',
        ),
    ]
