# Generated by Django 5.1.4 on 2025-03-05 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0003_alter_timetable_entries'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='entries',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='crc.timetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='crc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.faculty'),
        ),
    ]
