# Generated by Django 5.1.4 on 2025-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0004_remove_crc_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='crc',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
