# Generated by Django 5.1.4 on 2025-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0005_alter_crcprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
