# Generated by Django 5.1.4 on 2025-02-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0005_crc_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crc',
            name='phone_number',
        ),
    ]
