# Generated by Django 5.1.4 on 2025-03-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0006_timetableentry_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_fully_completed',
            field=models.BooleanField(default=False),
        ),
    ]
