# Generated by Django 5.1.4 on 2025-02-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0007_crcprofile_delete_crc'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crcprofile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='crcprofile',
            name='faculty',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crc_faculty', to='teacher.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crcprofile',
            name='valid_until',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
