# Generated by Django 5.1.4 on 2025-03-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0007_timetable_is_fully_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_fully_completed',
        ),
    ]
