# Generated by Django 5.1.4 on 2025-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0008_remove_crcprofile_employee_id_crcprofile_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crcprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='crcprofile',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='crcprofile',
            name='employee_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
