# Generated by Django 5.1.4 on 2025-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0008_alter_timetableentry_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(default='2021-2025', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
