# Generated by Django 5.1.4 on 2025-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0009_timetable_academic_year_timetable_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crcprofile',
            name='academic_year',
            field=models.CharField(default='2021-2025', max_length=9),
            preserve_default=False,
        ),
    ]
