# Generated by Django 5.1.4 on 2025-03-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0011_subject_academic_year_subject_branch_subject_crc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='crc',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
    ]
