# Generated by Django 5.1.4 on 2025-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0013_subject_academic_year_subject_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
