# Generated by Django 5.1.4 on 2025-03-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0014_remove_subject_academic_year_remove_subject_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='crc',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='crc.crcprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
