# Generated by Django 5.1.4 on 2025-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0015_subject_crc_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crcprofile',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
    ]
