# Generated by Django 5.1.4 on 2025-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0006_timetableentry_is_completed'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.ManyToManyField(related_name='faculty_assigned', through='crc.TimetableEntry', to='crc.subject'),
        ),
    ]
