# Generated by Django 5.1.4 on 2025-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='periods',
            field=models.JSONField(),
        ),
    ]
