# Generated by Django 5.1.4 on 2025-03-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_attendancesession_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.faculty'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
