# Generated by Django 5.1.4 on 2025-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_attendancesession_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
