# Generated by Django 5.1.4 on 2025-02-23 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('year', models.PositiveIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('phone_number', models.CharField(max_length=15)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('is_lateral_entry', models.BooleanField(default=False)),
                ('face_descriptor', models.JSONField()),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='student.student')),
            ],
        ),
    ]
