# Generated by Django 5.1.4 on 2025-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_descriptor',
            field=models.JSONField(),
        ),
    ]
