# Generated by Django 5.1.4 on 2025-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
