# Generated by Django 5.1.4 on 2025-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_face_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_descriptor',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
