# Generated by Django 5.1.4 on 2025-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_devicereregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
