services:
  - type: web
    name: attendance-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: attendance_system.settings
