# Generated by Django 5.1.4 on 2025-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('crc', 'CRC')], max_length=20, null=True),
        ),
    ]
