# Generated by Django 5.1.4 on 2025-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_branch_head_branch_head_of_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
