# Generated by Django 5.1.4 on 2025-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_superuser_common_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('crc', 'CRCProfile')], max_length=20, null=True),
        ),
    ]
