# Generated by Django 5.1.4 on 2025-02-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='is_active',
        ),
    ]
