# Generated by Django 5.1.4 on 2025-02-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_superadmin_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='last_login',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
